version: '3.9'

services:

  mysql:
    image: mysql:8
    container_name: library_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
      MYSQL_USER: markuser
      MYSQL_PASSWORD: Adeyoola01
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build: .
    container_name: library_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: markuser
      DB_PASSWORD: Adeyoola01
      DB_NAME: library_db

volumes:
  mysql_data:
